### ISSUE TITLE
Titulo do app ta meio estranho.

### ISSUE THREAD

**Issue by shadowruge** [andrersp/aplicativo-gasto-viagem#1]
Bom dia DEV, venho aqui para primeiro te parabenizar, <p>e te dar um toque porque acontece comigo também.<p> o nome do app ta meio estranho ou eu não entendi a proposta (
apricativo-gasto-viagem) .<p> não seria 'aplicativo' ou melhor que é como fasso 'app'.<p> bom dia e comtinue assim

**Comment by andrersp** [comment]
é um app somente de estudos. 
No momento o foco é somente entender a linguagem. 

Mas obrigado pelo seu comentário. 

Abs!
